blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/ThatGuySam/brentevents/discussions
    about: Ask questions or start a discussion about the calendar
